"""empty message

Revision ID: 43da7b82c4e0
Revises: dc196956caca
Create Date: 2023-09-28 16:48:24.774391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43da7b82c4e0'
down_revision = 'dc196956caca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
