"""empty message

Revision ID: 89e4e59d4a36
Revises: d1baa336e0b2
Create Date: 2023-09-25 11:33:45.489001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e4e59d4a36'
down_revision = 'd1baa336e0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('last_scraped', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_site_id_sites'), 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_site_id_sites'), type_='foreignkey')
        batch_op.drop_column('site_id')

    op.drop_table('sites')
    # ### end Alembic commands ###
