"""empty message

Revision ID: 9548c8f296ac
Revises: 89e4e59d4a36
Create Date: 2023-09-25 12:00:46.273014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9548c8f296ac'
down_revision = '89e4e59d4a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('data_path')

    # ### end Alembic commands ###
