"""empty message

Revision ID: dc196956caca
Revises: a2d295777365
Create Date: 2023-09-28 16:44:03.873226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc196956caca'
down_revision = 'a2d295777365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coords_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_coords_id_coords'), 'coords', ['coords_id'], ['id'])
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_events_coords_id_coords'), type_='foreignkey')
        batch_op.drop_column('coords_id')

    op.drop_table('coords')
    # ### end Alembic commands ###
